language: node_js
node_js:
  - stable
  - lts/*
  - 6.9
env:
  - WEBPACK_VERSION=3 VUE_LOADER_VERSION=^14.0.0
  - WEBPACK_VERSION=4 VUE_LOADER_VERSION=^15.0.0
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm rm vue-loader
  - npm install webpack@$WEBPACK_VERSION vue-loader@$VUE_LOADER_VERSION --ignore-scripts || true
script:
  - npm test